### ISSUE TITLE
Neighbourhood Warmth Project Outline

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/neighbourhood-warmth#1]
From  my point of view it would be good to be able to answer the following questions:

What is our overall goal with Neighbourhood Warmth - what do we want to achieve?

And once that's completely concrete:

What steps do we need to take to get there?
What do we need from mySociety to get there?
What do we need from outside mySociety to get there?
Who can we ask to help us from outside mySociety?
How much time do we need to get there?

**Comment by sequencefree** [comment]
Hiya @JenMysoc !

I'm going to respond to above here for now because I'm starting to think we might be better off using this repo to keep track of work on this so that our external partner has the option of collaborating here.

So here goes:

**What is our overall goal with Neighbourhood Warmth - what do we want to achieve?**

I don't think this is completely concrete, but I think establishing a partnership will help with that. I think a high-level goal could be: **Understand mySociety's role in accelerating a fair transition of the UK home energy sector.**

**What steps do we need to take to get there?**

- [ ] @sequencefree to establish a partnership for [the Alpha stage of the project](https://www.gov.uk/service-manual/agile-delivery/how-the-alpha-phase-works), using a Memorandum of Understanding or similar written document to agree key aspects of the collaboration e.g. questions and assumptions we want to test, activities.
- [ ] @sequencefree to establish a stakeholder panel of maybe 4-12 people to provide feedback throughout the Alpha stage of the project and manage engagement agreed with partners e.g. Slack channel, monthly meetings from November 2022?
- [ ] @sequencefree to draft research briefs: 1) for literature review of a few home energy studies, unless our partner has already absorbed this information; 2) key questions identified by our partner and/or stakeholder panel.
- [ ] **[Someone @ mySociety]** does the research or commissions an external researcher to do so.
- [ ] @sequencefree to establish ways of working with our partner e.g. Slack channel, GitHub repo, weekly 1/2hr meetings.
- [ ] @sequencefree to arrange joint meetings with our partner and other potential collaborators for remainder of 2022.
- [ ] @sequencefree to start blogging about the project on a monthly basis from November 2022 and maintain contact with interested stakeholders who aren't part of the stakeholder group e.g. Sian Ferguson @ Sainsbury's Family Charitable Trust.
- [ ] @zarino to guide development of Alpha stage solutions from January 2022, with key decisions made by our partner.
- [ ] Partner to deploy Alpha stage solutions in at least one community, with options for broader deployment (e.g. by another collaborator – such as as [First Thermal](https://first-thermal.co.uk/) franchisee –  in a different community), from March 2023.
- [ ] Partner and @sequencefree gather and share feedback from users during Alpha stage, which estimated to last in the range of 1-6 months.
- [ ] **[Someone @ mySociety]** analyses, synthesises and shares insights from testing.
- [ ] @zarino produces and publishes a summary report of what we learnt during the Alpha stage.
- [ ] If @zarino decides a promising solution has emerged from Alpha stage, move to [Beta stage](https://www.gov.uk/service-manual/agile-delivery/how-the-beta-phase-works).
- [ ] @sequencefree explores options to scale testing with key partners e.g. Frome Town Council, Citizens Advice, UK Green Building Council council retrofit forum.
- [ ] @MyfanwyNixon develops and deploys comms plan for public launch and ongoing promotion.
- [ ] **[Someone @ mySociety]** creates a technical specification for Beta stage and builds the service.
- [ ] If @zarino decides a promising solution has emerged from Beta stage, move to [Live](https://www.gov.uk/service-manual/agile-delivery/how-the-live-phase-works).


**What do we need from mySociety to get there?**

Likely to require input on outreach and networks, design, software development, research and maybe policy (e.g. to translate data generated by service to recommendations for policymakers).


**What do we need from outside mySociety to get there?**

A partner that is responsible for: 

1. Steering the work.
2. Final decisions on solutions design options.
3. Providing access to potential users and deploying solutions to them for testing.
4. Gathering and sharing feedback from testers.


**Who can we ask to help us from outside mySociety?**

I'm imagining a network of networks approach, where our partner and stakeholder group broaden our reach if we need to ask for help.


**How much time do we need to get there?**

Is this something we could explore through Climate Programme team estimation using planning poker and/or other methods?

Many of the steps outlined above could be broken down further into smaller steps, maybe best done before team estimation.

Maybe a next step is to invite people to take ownership of big steps so that someone is responsible for breaking them down.

**Comment by JenMysoc** [comment]
this is done! we have a project outline https://docs.google.com/document/d/1BnvJd2olHi2HTO0iR4G9Rjxfqa_wM75ZUYekn0sUWjo/edit
