### ISSUE TITLE
Enter postcode to show nearby teams

### ISSUE THREAD

**Issue by zarino** [mysociety/neighbourhood-warmth#14]
Need a function that, given a postcode, returns a list of nearby teams, perhaps sorted by proximity.

Hooked up to a postcode search fields on the homepage and search results page.

May be that we want to give _teams_ a “location” (coordinates?) or we might be able to _guess_ a team’s location based on the location of its member(s).

**Comment by zarino** [comment]
@struan is investigating this in https://github.com/mysociety/neighbourhood-warmth/issues/25

**Comment by struan** [comment]
The technical side of this is done, need to complete the design side, show a map etc.

**Comment by sequencefree** [comment]
@zarino Jack and I discussed what testers will see, and occurred to us that we could show teams that are doing something other than assessments to probe [our first pair of research questions](https://docs.google.com/document/d/1BnvJd2olHi2HTO0iR4G9Rjxfqa_wM75ZUYekn0sUWjo/edit#heading=h.fz3mghr1s8yn).

Assuming our first workshop happens on 19 June, I'm guessing it'll be possible to pre-populate the Alpha with dummy team data closer to the time without additional work to what is already planned but let me know if you think otherwise.

One additional feature that I could create a ticket for is something like a dialogue box so that if users try to join a team doing anything other than an assessment, they're served a message saying "Here's why we think you should do an assessment..." with a button or two to let them carry on or return to search results. Any preference for doing that vs folding into this ticket?

**Comment by zarino** [comment]
> Assuming our first workshop happens on 19 June, I'm guessing it'll be possible to pre-populate the Alpha with dummy team data closer to the time without additional work to what is already planned but let me know if you think otherwise.

@sequencefree I’ve created a ticket for this: https://github.com/mysociety/neighbourhood-warmth/issues/37

> One additional feature […] Any preference for doing that vs folding into this ticket?

I’ve created a new ticket for that too: https://github.com/mysociety/neighbourhood-warmth/issues/38

**Comment by sequencefree** [comment]
> > Assuming our first workshop happens on 19 June, I'm guessing it'll be possible to pre-populate the Alpha with dummy team data closer to the time without additional work to what is already planned but let me know if you think otherwise.
> 
> @sequencefree I’ve created a ticket for this: #37
> 
> > One additional feature […] Any preference for doing that vs folding into this ticket?
> 
> I’ve created a new ticket for that too: #38

Thanks Zarino! I will stop asking about creating tickets and just create them from now on until someone says to stop!

**Comment by zarino** [comment]
Given all the outstanding suggestions have been moved into their own tickets (#29 #37 #38) I think we can close this one.
